apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexops.fullname" . }}-backend
  labels:
    {{- include "nexops.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.backend.port | quote }}
    prometheus.io/path: {{ .Values.metrics.path | quote }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "nexops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexops.fullname" . }}-frontend
  labels:
    {{- include "nexops.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "nexops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexops.postgresHost" . }}
  labels:
    {{- include "nexops.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    {{- include "nexops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexops.redisHost" . }}
  labels:
    {{- include "nexops.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "nexops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
{{- end }}
