apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexops-staging

resources:
  - ../../base

images:
  - name: nexops-backend
    newName: docker.io/haritejarv/nexops-backend
    newTag: latest
  - name: nexops-frontend
    newName: docker.io/haritejarv/nexops-frontend
    newTag: latest

replicas:
  - { name: backend,  count: 2 }
  - { name: frontend, count: 1 }

patches:
  - target: { kind: Ingress, name: nexops }
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nexops-staging.local

configMapGenerator:
  - name: nexops-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - SEED_ENABLED=true
